version: "2"

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 3

checks:
  argument-count:
    enabled: false
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 15

exclude_patterns:
  - ".*"
  - "*.cfg"
  - "*.md"
  - "*.txt"
  - "*.yml"
  - "*.yaml"
  - "custom_build.py"
  - "COPYING"
  - "**/__*"
  - "**/*.c"
  - "**/*.ccp"
  - "binder/*"
  - "data/*"
  - "docs/*"
  - "scripts/*"
  - "src/*"
  - "test/*"
