repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies: [
          'flake8-bugbear==22.4.25',
          ]
