channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # docs specific packages
  - mock
  - sphinx
  - sphinx_bootstrap_theme

  # gimme packages (without the motif discovery tools)
  - bioconda::biofluff >=3.0.4    # Necessary for coverage_table()
  - configparser
  - conda-forge::diskcache
  - conda-forge::feather-format
  - bioconda::genomepy >=0.13.0
#  - ipywidgets                    # Necessary for progress bar in Jupyter notebook
  - conda-forge::iteround
  - jinja2
  - bioconda::logomaker
  - loguru
  - matplotlib-base >=3.3         # https://matplotlib.org/stable/devel/min_dep_policy.html#list-of-dependency-versions
  - numpy >=1.18                  # https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table
  - pandas >=1.3.0                # Necessary for ExtraStyler.render()
  - bioconda::pybedtools >=0.9.0
  - bioconda::pysam >=0.16
  - python >=3.6
  - python-xxhash
  - conda-forge::qnorm  >=0.8.1
  - scikit-learn >=0.23.2         # https://scikit-learn.org/stable/install.html#installing-the-latest-release
  - scipy >=1.5                   # https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy
  - seaborn >=0.10.1
  - statsmodels
  - tqdm >=4.46.1
  - xdg
  - xgboost >=1.0.2
