## run travis on these branches (and all PRs)
branches:
  only:
  - master
  - develop

os: linux
dist: focal
language: minimal

env:
  global:
    - CC_TEST_REPORTER_ID=3865090108d29191b1d34760d2ed5825d67b7566f0f87090e688b7513fdef063

before_install:
  # setup miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH;
  - conda config --set always_yes True

install:
  - conda install conda-forge::mamba
  - mamba env create -f requirements.yaml
  - source activate gimme
  - python setup.py build  # installs the motif discovery tools
  - pip install -e .  # installs gimme (in editable mode)

before_script:
  # install Code Climate test coverage reporter
  - wget -O cc-test-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  # generate the config and print the cache location
  - python -c 'from gimmemotifs.config import CACHE_DIR;print(CACHE_DIR)'
  # run the tests
  - pytest -vvv --disable-pytest-warnings --cov=scripts --cov=gimmemotifs --cov-report=xml test/

after_script:
  # upload test coverage data to Code Climate
  - ./cc-test-reporter after-build -t coverage.py --exit-code $TRAVIS_TEST_RESULT
