name: gimme
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
#  - bioconda::biofluff >=3.0.4  # TODO: biofluff added, version set to bioconda. is this needed?
#  - bioconda::bedtools  # TODO: is this needed with pybedtools? under "host" on bioconda
  - conda-forge::gcc  # Necessary to install motif discovery tools
  - configparser
  - conda-forge::diskcache
  - conda-forge::feather-format
  - bioconda::genomepy >=0.11.1
  - ipywidgets  # Necessary for progress bar in Jupyter notebook
  - conda-forge::iteround
  - jinja2
  - bioconda::logomaker
  - loguru
  - matplotlib-base >=3.1.2
#  - ncurses >=6.1 # TODO: is this needed with loguru? version set to bioconda
  - numpy >= 1.6.0
  - pandas >=1.0.3
#  - pillow >=0.7.1.2  # TODO: is this needed? version set to bioconda
  - pyarrow >=0.16.0
  - bioconda::pybedtools >=0.9.0
  - bioconda::pysam >=0.16
  - python >=3.8
  - python-xxhash
#  - pyyaml >=3.10  # TODO: is this needed?
  - conda-forge::qnorm  >=0.8.1
  - scikit-learn >=0.23.2  # TODO: version set to bioconda
  - scipy >=1.4.1
  - seaborn >=0.10.1  # TODO: version set to bioconda
  - statsmodels
  - tqdm >=4.46.1  # TODO: version set to bioconda
#  - ucsc-bigbedtobed  # TODO: is this needed?
#  - ucsc-genepredtobed  # TODO: is this needed?
  - xdg
  - xgboost >=1.0.2

# motif discovery tools
  # AMD                           # installed with `pip install .`
  # BioProspector                 # installed with `pip install .`
  # ChIPMunk                      # installed with `pip install .`
  - bioconda::dinamo >=1.0
  # DREME
  - bioconda::gadem >=1.3.1
  # HMS                           # installed with `pip install .`
  - bioconda::homer >=4.11
  # Improbizer                    # installed with `pip install .`
  # MDmodule                      # installed with `pip install .`
  - bioconda::meme >=5.4.1
  # MEMEW                         # installed with `pip install .`
  # MotifSampler                  # installed with `pip install .`
  # Posmo                         # installed with `pip install .`
  - bioconda::prosampler >=1.0
  # RPMCMC
  - bioconda::trawler >=2.0
  - bioconda::weeder >=2.0
  - bioconda::xxmotif >=1.6
  - bioconda::yamda >=0.1.00e9c9d

# development
  - conda-forge::black=22.3.0  # same as in .pre-commit-config.yaml
  - conda-forge::flake8=4.0.1  # same as in .pre-commit-config.yaml
  - conda-forge::flake8-bugbear=22.4.25  # same as in .pre-commit-config.yaml
  - conda-forge::isort=5.10.1  # same as in .pre-commit-config.yaml
  - conda-forge::pre-commit
  - conda-forge::pytest
  - conda-forge::pytest-cov
#  - conda-forge::twine  # TODO: is this still needed?
