name: gimme
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::biofluff >=3.0.4    # Necessary for coverage_table()
  - configparser
  - conda-forge::diskcache
  - conda-forge::feather-format
  - bioconda::genomepy >=0.13.0
  - ipywidgets                    # Necessary for progress bar in Jupyter notebook
  - conda-forge::iteround
  - jinja2
  - bioconda::logomaker
  - loguru
  - matplotlib-base >=3.3         # https://matplotlib.org/stable/devel/min_dep_policy.html#list-of-dependency-versions
  - numpy >=1.18                  # https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table
  - pandas >=1.3.0                # Necessary for ExtraStyler.render()
  - bioconda::pybedtools >=0.9.0
  - bioconda::pysam >=0.16
  - python >=3.6
  - python-xxhash
  - conda-forge::qnorm  >=0.8.1
  - scikit-learn >=0.23.2         # https://scikit-learn.org/stable/install.html#installing-the-latest-release
  - scipy >=1.5                   # https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy
  - seaborn >=0.10.1
  - statsmodels
  - tqdm >=4.46.1
  - xdg
  - xgboost >=1.0.2

# motif discovery tools
  - conda-forge::gcc              # Necessary to install motif discovery tools
  # AMD                           # installed from source
  # BioProspector                 # installed from source
  # ChIPMunk                      # installed from source
  - bioconda::dinamo >=1.0
  # DREME
  - bioconda::gadem >=1.3.1
  # HMS                           # installed from source
  - bioconda::homer >=4.11
  # Improbizer                    # installed from source
  # MDmodule                      # installed from source
  - bioconda::meme >=5.4.1
  # MEMEW                         # installed from source
  # MotifSampler                  # installed from source
  # Posmo                         # installed from source
  - bioconda::prosampler >=1.0
  # RPMCMC
  - bioconda::trawler >=2.0
  - bioconda::weeder >=2.0
  - bioconda::xxmotif >=1.6
  - bioconda::yamda >=0.1.00e9c9d

# development packages
  - conda-forge::black=22.3.0            # same as in .pre-commit-config.yaml
  - conda-forge::flake8=4.0.1            # same as in .pre-commit-config.yaml
  - conda-forge::flake8-bugbear=22.4.25  # same as in .pre-commit-config.yaml
  - conda-forge::isort=5.10.1            # same as in .pre-commit-config.yaml
  - conda-forge::pre-commit
  - conda-forge::pytest
  - conda-forge::pytest-cov
