--- #YAML:1.0
name:               Algorithm-Cluster
version:            1.49
abstract:           Perl interface to the C Clustering Library
author:
    - John Nolan and Michiel de Hoon (mdehoon "AT" gsc.riken.jp)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
