static char *cisml_dts = "<?xml version='1.0' encoding='UTF-8' standalone='yes'?>\n"
  "<!-- Document definition -->\n"
  "<!-- http://zlab.bu.edu/~phaverty/SupplementalData/CisML/cisml.dtd -->\n"
  "<!DOCTYPE cis-element-search[\n"
  "<!ELEMENT cis-element-search (program-name, parameters, (pattern | multi-pattern-scan)*)>\n"
  "<!ELEMENT program-name (#PCDATA)>\n"
  "<!ELEMENT parameters (\n"
  "  pattern-file, \n"
  "  sequence-file, \n"
  "  background-seq-file?,\n"
  "  pattern-pvalue-cutoff?,\n"
  "  sequence-pvalue-cutoff?,\n"
  "  site-pvalue-cutoff?,\n"
  "  sequence-filtering,\n"
  "  ANY*\n"
  " )>\n"
  "<!ELEMENT command-line (#PCDATA)>\n"
  "<!ELEMENT pattern-file (#PCDATA)>\n"
  "<!ELEMENT sequence-file (#PCDATA)>\n"
  "<!ELEMENT background-seq-file (#PCDATA)>\n"
  "<!ELEMENT pattern-pvalue-cutoff (#PCDATA)>\n"
  "<!ELEMENT sequence-pvalue-cutoff (#PCDATA)>\n"
  "<!ELEMENT site-pvalue-cutoff (#PCDATA)>\n"
  "<!ELEMENT sequence-filtering EMPTY>\n"
  "<!ELEMENT multi-pattern-scan (pattern+, ANY*)>\n"
  "<!ELEMENT pattern (scanned-sequence+, ANY*)>\n"
  "<!ELEMENT scanned-sequence (matched-element*, ANY*)>\n"
  "<!ELEMENT matched-element (sequence)>\n"
  "<!ELEMENT sequence (#PCDATA)>\n"
  "<!ATTLIST cis-element-search\n"
	"xmlns:xsi CDATA #IMPLIED\n"
	"xmlns:mem CDATA #IMPLIED\n"
	"xsi:schemaLocation CDATA #IMPLIED\n"
  ">\n"
  "<!ATTLIST sequence-filtering\n"
	  "on-off CDATA #REQUIRED\n"
	  "type CDATA #IMPLIED\n"
  ">\n"
  "<!ATTLIST multi-pattern-scan\n"
	  "score CDATA #IMPLIED\n"
	  "pvalue CDATA #IMPLIED\n"
  ">\n"
  "<!ATTLIST pattern\n"
	  "accession CDATA #REQUIRED\n"
	  "name CDATA #REQUIRED\n"
	  "pvalue CDATA #IMPLIED\n"
	  "score CDATA #IMPLIED\n"
	  "db CDATA #IMPLIED\n"
	  "lsid CDATA #IMPLIED\n"
  ">\n"
  "<!ATTLIST scanned-sequence\n"
	  "accession CDATA #REQUIRED\n"
	  "name CDATA #REQUIRED\n"
	  "score CDATA #IMPLIED\n"
	  "pvalue CDATA #IMPLIED\n"
	  "length CDATA #IMPLIED\n"
	  "db CDATA #IMPLIED\n"
	  "lsid CDATA #IMPLIED\n"
  ">\n"
  "<!ATTLIST matched-element\n"
	  "start CDATA #REQUIRED\n"
	  "stop CDATA #REQUIRED\n"
	  "score CDATA #IMPLIED\n"
	  "pvalue CDATA #IMPLIED\n"
	  "clusterid CDATA #IMPLIED\n"
  ">\n"
  "\n]>\n";
