#!/usr/bin/env python
# Copyright (c) 2013-2019 Simon van Heeringen <simon.vanheeringen@gmail.com>
#
# This module is free software. You can redistribute it and/or modify it under
# the terms of the MIT License, see the file COPYING included with this
# distribution.
import sys
from gimmemotifs.cli import cli

if __name__ == "__main__":
    cli(sys.argv[1:])
