/* 
 * $Id: template-css.js 2393 2008-01-27 00:10:11Z tbailey $
 * 
 * $Log$
 * Revision 1.2  2006/03/07 23:30:20  nadya
 * merge branches v3_5_1 and v3_5_2 back to the trunk
 *
 * Revision 1.1.2.1  2006/02/22 20:47:48  nadya
 * initial revision. enabling styling with js and css
 *
 */

/* 
  Set global html_path if the user has not done so.
  This needs to be set in forms generated by cgi scripts that
  live in the directory below the html directory.
*/
if (!window.html_path) {
  var html_path = './'
}

document.write("<link href=" + html_path + "style-default.css rel=stylesheet type=text/css>");

/*var root = './'; 		/* in html directory; override this 
				with '../' if in cgi-bin */
